export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const AUTH_ROUTE = '/auth'
export const REGISTRATION_ROUTE = '/registration'
export const HOME_ROUTE = '/'
export const ABOUT_US_ROUTE = '/aboutUs'
export const GET_STARTED_ROUTE = '/getStarted'
export const MARKET_ROUTE = '/market'